/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ControlarHorario.view;

import ControlarHorario.controller.ControlarHorarioController;
import ControlarHorario.model.ControlarHorario;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo Mendes
 */
public class ProjetoControlador extends javax.swing.JDialog {

    /**
     * Creates new form ProjetoPrincipal
     */
    public ProjetoControlador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    LocalDateTime dataHoraLocal = LocalDateTime.now(); // Criando objeto do tipo data
        
    LocalTime horaInicial = dataHoraLocal.toLocalTime(); // Pegando a hora local

    LocalDate dataInicial = dataHoraLocal.toLocalDate(); // Pegando a data local
    
    DateTimeFormatter horaFormatter = DateTimeFormatter.ofPattern("HH:mm:ss"); // Criando um formatador para hora
    DateTimeFormatter dataFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");  // Criando um formatador para Data

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeProjeto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabelDataAtual = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelHorarioInicio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonComecar = new javax.swing.JButton();
        jButtonParar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonSair = new javax.swing.JButton();
        jButtonVisualizador = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabelHorarioFinal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelTempoGasto = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButtonZerar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelDataFinal = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabelMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controlador de Horário - Github: gustavocarmomendes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3), "Controlador de Tempo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 3, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "Iniciar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Nome do Projeto:");

        jTextFieldNomeProjeto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Descrição do Projeto:");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Data Atual:");

        jLabelDataAtual.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelDataAtual.setText("XX/XX/XXXX");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Horário de Início:");

        jLabelHorarioInicio.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelHorarioInicio.setText("XX:XX:XX");

        jButtonComecar.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jButtonComecar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonComecar.setText("Começar");
        jButtonComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComecarActionPerformed(evt);
            }
        });

        jButtonParar.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jButtonParar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonParar.setText("Parar");
        jButtonParar.setEnabled(false);
        jButtonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHorarioInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomeProjeto)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDataAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHorarioInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonParar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jButtonSair.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(51, 51, 255));
        jButtonSair.setText("Menu Principal");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonVisualizador.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jButtonVisualizador.setForeground(new java.awt.Color(51, 51, 255));
        jButtonVisualizador.setText("Visualizador");
        jButtonVisualizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVisualizador, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVisualizador, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "Tempo de Trabalho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Horário Final:");

        jLabelHorarioFinal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelHorarioFinal.setText("XX:XX:XX");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Tempo Gasto:");

        jLabelTempoGasto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelTempoGasto.setText("XX:XX:XX");

        jButtonZerar.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jButtonZerar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonZerar.setText("Zerar");
        jButtonZerar.setEnabled(false);
        jButtonZerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZerarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Data Final:");

        jLabelDataFinal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelDataFinal.setText("XX/XX/XXXX");

        jLabelMensagem.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelMensagem.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonZerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabelDataFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHorarioFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jLabelTempoGasto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator6)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDataFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHorarioFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTempoGasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jButtonZerar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisualizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizadorActionPerformed
        dispose();
        ProjetoVisualizador dialog = new ProjetoVisualizador(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonVisualizadorActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
        ProjetoInicio dialog = new ProjetoInicio(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComecarActionPerformed
        
       // Ações
        
        String strNomeProjeto = jTextFieldNomeProjeto.getText();    // Pegando informação
        String strDescProjeto = jTextAreaDescricao.getText();       // do que o usuário inseriu
        
        if(!(strNomeProjeto.equals("") || strDescProjeto.equals(""))) { // Verificando se o usuário informou corretamente as informações
        
            String horaFormatada = horaInicial.format(horaFormatter); // Pegando  a hora inicial, formtando e colocando em uma String
            String dataFormatada = dataInicial.format(dataFormatter); // Pegando a data inicial, formtando e colocando em uma String

            jLabelDataAtual.setText(dataFormatada);     // Setando as informações para o usuário
            jLabelHorarioInicio.setText(horaFormatada); // informações para o usuário

            // Animações da View
            jButtonComecar.setEnabled(false);
            jButtonParar.setEnabled(true);
            jTextAreaDescricao.setEnabled(false);
            jTextFieldNomeProjeto.setEnabled(false);
            jButtonSair.setEnabled(false);
            jButtonVisualizador.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "POR FAVOR, INSIRA AS INFORMAÇÕES CORRETAMENTE!");
        }
        
    }//GEN-LAST:event_jButtonComecarActionPerformed

    private void jButtonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararActionPerformed
        
        // Animações da View
        jButtonZerar.setEnabled(true);
        jButtonParar.setEnabled(false);
        jButtonSair.setEnabled(false);
        jButtonVisualizador.setEnabled(false);
        jButtonSair.setEnabled(true);
        jButtonVisualizador.setEnabled(true);
        
        // Código
        
        LocalDateTime dataHoraLocalFinal = LocalDateTime.now(); // Criando objeto do tipo data
        
        LocalTime horaFinal = dataHoraLocalFinal.toLocalTime(); // Pegando a hora local

        LocalDate dataFinal = dataHoraLocalFinal.toLocalDate(); // Pegando a data local
        
        String horaInicialFormatada = horaInicial.format(horaFormatter); // Pegando o horário inical salvo, formatando e colocando em uma string
        String horaFinalFormatada = horaFinal.format(horaFormatter); // Pegando o horário final, formatando e colocando em uma string
        
        String strDataInicial = dataInicial.toString(); // Pegando a data inicial salva e colocando em uma string
        String strDataFinal = dataFinal.toString(); // pegando a data atual e salvando em uma string
        
        String strDataHoraInicial = strDataInicial.concat(" " + horaInicialFormatada); // Concatenando a data juntamente com o horário inicial
        String strDataHoraFinal = strDataFinal.concat(" " + horaFinalFormatada); // Concatenando a data juntamente com o horário final
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"); // Criando um formatador para a data e horário juntos
        
        LocalDateTime dt1 = LocalDateTime.parse(strDataHoraInicial, formatter); // Formatando a data e horário inicial
        LocalDateTime dt2 = LocalDateTime.parse(strDataHoraFinal, formatter); // Formatando a data e horário final

        long diferencaSeg = Duration.between(dt1, dt2).toSecondsPart(); // Pegando a diferença em segundos
        long diferencaMin = Duration.between(dt1, dt2).toMinutesPart(); // Pegando a diferença em minutos
        long diferencaHor = Duration.between(dt1, dt2).toHoursPart(); // Pegando a diferença em horas
        
        String strDataFinalFormatada = dataFinal.format(dataFormatter); // Formatando a data final para mostrar ao usuário
        
        String strDiferencaHora = diferencaHor + ":" + diferencaMin + ":" + diferencaSeg; // juntando as informações de horas obtidas na linha 441
        
        jLabelDataFinal.setText(strDataFinalFormatada); // Imprimindo na tela do usuário a data final
        jLabelHorarioFinal.setText(horaFinalFormatada); // Imprimindo na tela do usuário o horário final
        jLabelTempoGasto.setText(strDiferencaHora); // Imprimindo na tela do usuário o tempo gasto
        jLabelMensagem.setText("Excelente Trabalho!"); // Imprimindo na tela do usuário uma mensagem de parabéns
        
        ControlarHorarioController horario = new ControlarHorarioController(); // Criando um objeto da classe Controller
        
        // Setando as informações do objeto, obs: Todas as informações são passadas como String pois nossa classe de Controle irá formatar
        horario.setNomeProjeto(jTextFieldNomeProjeto.getText());
        horario.setDescricao(jTextAreaDescricao.getText());
        horario.setDataInical(dataInicial.format(dataFormatter));
        horario.setHorarioInical(horaInicialFormatada);
        horario.setDataFinal(dataFinal.format(dataFormatter));
        horario.setHorarioFinal(horaFinalFormatada);
        horario.setHorarioTotal(strDiferencaHora);
        
        try { // Fazendo um Try-Cath para evitar qualquer tipo de problema que de no Banco de Dado
            horario.salvar( 
                    horario.getNomeProjeto(),
                    horario.getDescricao(),
                    horario.getDataInical(),                    // Passando as informações por paramêtro
                    horario.getHorarioInical(),               // para o método agir de acordo com a sua função
                    horario.getDataFinal(),
                    horario.getHorarioFinal(),
                    horario.getHorarioTotal());
                    JOptionPane.showMessageDialog(this, "Horário salvo com sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Não foi possível salvar o horário!" + e.getLocalizedMessage());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data possui formato inválido!" + e.getLocalizedMessage());
        }
        
    }//GEN-LAST:event_jButtonPararActionPerformed

    private void jButtonZerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZerarActionPerformed
        jTextAreaDescricao.setText("");
        jTextFieldNomeProjeto.setText("");
        jLabelDataAtual.setText("XX/XX/XXXX");
        jLabelHorarioInicio.setText("XX:XX:XX");
        jTextAreaDescricao.setEnabled(true);
        jTextFieldNomeProjeto.setEnabled(true);
        jButtonComecar.setEnabled(true);
        jButtonZerar.setEnabled(false);
        jLabelDataFinal.setText("XX/XX/XXXX");
        jLabelHorarioFinal.setText("XX:XX:XX");
        jLabelTempoGasto.setText("XX:XX:XX");
        jLabelMensagem.setText("");
    }//GEN-LAST:event_jButtonZerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComecar;
    private javax.swing.JButton jButtonParar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVisualizador;
    private javax.swing.JButton jButtonZerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDataAtual;
    private javax.swing.JLabel jLabelDataFinal;
    private javax.swing.JLabel jLabelHorarioFinal;
    private javax.swing.JLabel jLabelHorarioInicio;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelTempoGasto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
